### ISSUE TITLE
Hourly Forecasts

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-project-22.AUG.PREP.1#1]
Allow the user to put a time + date in to get an idea of what the weather will be like then. At the moment, it only displays the weather right now.

**Comment by juhiechandra** [comment]
This issue is marked as completed with pull request #21 under Issue No #18 
Done by @XooTB @hello-fri-end @juhiechandra

**Comment by Buly1601** [comment]
-- completed --
