### ISSUE TITLE
Create Secondary Navigation Bar

### ISSUE THREAD

**Issue by BabyElias** [MLH-Fellowship/prep-project-22.AUG.PREP.1#10]
![image](https://user-images.githubusercontent.com/95405559/183710250-32ec9516-8596-45f4-9673-332d7e3090f6.png)

Make secondary navigation bar with the following tabs. Each link should updated within the page just like :
![image](https://user-images.githubusercontent.com/95405559/183859070-f4a94c4e-9501-4f5e-bbf6-077eceb17af6.png)

**Comment by aakankshabhende** [comment]
@aakankshabhende @deepanshug4 
We will be working on this issue

**Comment by nawed2611** [comment]
me and @kartikmehta8 will be working on this

**Comment by Buly1601** [comment]
Nice!!!!

**Comment by Buly1601** [comment]
Fixed issue without conflicts.
