### ISSUE TITLE
Tab for music recommendation

### ISSUE THREAD

**Issue by BabyElias** [MLH-Fellowship/prep-project-22.AUG.PREP.1#11]
![image](https://user-images.githubusercontent.com/95405559/183711162-10799fdf-d326-4d4c-9efa-8d9d60becc00.png)
![image](https://user-images.githubusercontent.com/95405559/183860910-c652c0c8-815e-4b64-b654-e34b9dc5ccac.png)

Make the music recommendation tab, wherein playlist best suited to the weather of entered place is suggested.

**Comment by Buly1601** [comment]
Coool!

**Comment by Buly1601** [comment]
Fixed issue without conflicts.
