### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by BabyElias** [MLH-Fellowship/prep-project-22.AUG.PREP.1#16]
Add a footer for the website.
![image](https://user-images.githubusercontent.com/95405559/183862486-d420be8f-10eb-41a0-a92f-84147d67565e.png)

**Comment by Buly1601** [comment]
Yes!!!!! now we know who were the ones that created the amazing app :D

**Comment by Buly1601** [comment]
Fixed issue without conflicts.
