### ISSUE TITLE
Creating Header of React App

### ISSUE THREAD

**Issue by juhiechandra** [MLH-Fellowship/prep-project-22.AUG.PREP.1#18]
To work on:

- [ ] Weather API integration 
- [ ] Random Quote API integration

<img width="576" alt="Screenshot 2022-08-10 at 3 16 29 PM" src="https://user-images.githubusercontent.com/75068056/183871244-55a39cb0-a16a-44b6-939c-422a24fa2a41.png">

**Comment by juhiechandra** [comment]
Assigned to @juhiechandra @hello-fri-end @XooTB  Team

**Comment by Buly1601** [comment]
Fixed issue without conflicts.
