### ISSUE TITLE
Tab for Travel Recommendations 

### ISSUE THREAD

**Issue by juhiechandra** [MLH-Fellowship/prep-project-22.AUG.PREP.1#19]
- [X] Create this design
- [X] Integrate any travel recommendation API

<img width="717" alt="Screenshot 2022-08-10 at 3 24 36 PM" src="https://user-images.githubusercontent.com/75068056/183872848-fec3b1a3-9ad4-4df8-b4ab-2f7a748fd792.png">

**Comment by JooZef315** [comment]
hi @Buly1601 
it is merged without any conflicts in deepanshug's repo , so it can you merge and close it?

**Comment by juhiechandra** [comment]
Successfully Implemented!
