### ISSUE TITLE
Creating Micro Interaction on Guiding Text

### ISSUE THREAD

**Issue by juhiechandra** [MLH-Fellowship/prep-project-22.AUG.PREP.1#20]
- [ ] **Write a script file for changing of text that appears to guide users through the App**
<img width="450" alt="Screenshot 2022-08-10 at 3 27 26 PM" src="https://user-images.githubusercontent.com/75068056/183873415-56c09c80-cee7-4571-92b1-b4ee5bc2d8a5.png">

**Dependencies:**
Issues #9 

**ETA:**
Pick Up Next Week

**Assigned to:**
@juhiechandra @hello-fri-end @XooTB

**Comment by Buly1601** [comment]
-- done --
