### ISSUE TITLE
Helping the user bring the right things based on the weather

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-project-22.AUG.PREP.1#4]
- If it's raining, bring an umbrella
- If it's sunny, bring suncream
- If it's cold, bring a coat

**Comment by deepanshug4** [comment]
Hey, @Buly1601 please assign this to me @deepanshug4 and @aakankshabhende.

**Comment by Buly1601** [comment]
-- completed --
