### ISSUE TITLE
Re-Design App Concept

### ISSUE THREAD

**Issue by juhiechandra** [MLH-Fellowship/prep-project-22.AUG.PREP.1#8]
Design the React App 

Task completed:

- [x] Basic Layout
- [x] Color Scheme
- [x] Prototype

Pending:

- [ ]  _User Login UI_ (idea cancelled for now)
- [ ] _User authentication_  (idea cancelled for now)

**Comment by juhiechandra** [comment]
assign to @deepanshug4 @juhiechandra

**Comment by deepanshug4** [comment]
We have designed the basic layout and workflow of the application. You can check it out [here](https://www.figma.com/proto/rBp0Vmg9Dzl8qQW3AjchUU/Untitled?page-id=0%3A1&node-id=1%3A4&viewport=-560%2C499%2C0.35&scaling=contain&starting-point-node-id=1%3A4).

**Comment by juhiechandra** [comment]
Task completed:

- [x] Basic Layout
- [x] Color Scheme
- [x] Prototype

Pending:

- [ ]  User Login UI 
- [ ] User authentication

**Comment by Buly1601** [comment]
will wait on pending fixes :D

**Comment by juhiechandra** [comment]
Successful as of now! closing the issue
