### ISSUE TITLE
Create Main Navigation Bar

### ISSUE THREAD

**Issue by BabyElias** [MLH-Fellowship/prep-project-22.AUG.PREP.1#9]
![image](https://user-images.githubusercontent.com/95405559/183708830-819e2ae3-94b0-4d58-86da-74748f5e3913.png)
![image](https://user-images.githubusercontent.com/95405559/183858659-3f9497f4-2b9e-4942-9abc-622a59f3d8e9.png)

Make this top navbar(banner). Add MLH Prep Logo(Or custom logo for Major Weather Hacking) 
Also , add tabs for Planner and Login.

**Comment by aakankshabhende** [comment]
@aakankshabhende @deepanshug4
We will be working on this issue

**Comment by Buly1601** [comment]
This looks amazing!!!

**Comment by Buly1601** [comment]
Fixed issue without conflicts.
